title: WXPN's Blog
email: aswinkgopan@gmail.com
description: Exploring the depths of cyber security, one vulnerability at a time.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/wxpn
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/aswingopalakrishnan/

navigation:
  - name: About Me
    link: /index.html
  - name: System Design Concepts
    link: /docs/SystemDesign.html
  - name: Active Directory
    link: /docs/ActiveDirectory.html
    sublist:
      - name: Enumeration
        link: /docs/AD/enumeration.html
  - name: Malware Development
    link: /docs/malware-introduction.html
    sublist:
      - name: Hiding malware within an Image
        link: /docs/malware/malware-imagecon.html
      - name: Backdooring PE
        link: /docs/malware/backdooringPE.html
