title: WXPN
logo: /assets/img/logo.jpg
email: wxpn@gmail.com
description: Exploring the depths of cyber security, one vulnerability at a time.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/wxpn
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/aswingopalakrishnan/

navigation:
  - name: About Me
    link: /index.html
  - name: Malware Development
    sublist:
      - name: Hiding malware within an Image
        link: /docs/malware.html
    link: ./new-page.html
